version: '3.8'

services:
  # Development infrastructure only
  mongodb:
    image: mongo:7.0
    container_name: logitrack-mongodb-dev
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongodb_dev_data:/data/db
    networks:
      - logitrack-dev-network

  redis:
    image: redis:7-alpine
    container_name: logitrack-redis-dev
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_dev_data:/data
    networks:
      - logitrack-dev-network

  # Optional: MongoDB Admin UI
  mongo-express:
    image: mongo-express:1.0.0
    container_name: logitrack-mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://admin:password@mongodb:27017/
      ME_CONFIG_BASICAUTH: false
    depends_on:
      - mongodb
    networks:
      - logitrack-dev-network

  # Optional: Redis Admin UI
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: logitrack-redis-commander
    restart: unless-stopped
    ports:
      - "8082:8081"
    environment:
      REDIS_HOSTS: local:redis:6379
    depends_on:
      - redis
    networks:
      - logitrack-dev-network

networks:
  logitrack-dev-network:
    driver: bridge

volumes:
  mongodb_dev_data:
  redis_dev_data: